### ISSUE TITLE
authenticate() takes exactly 0 arguments (1 given)

### ISSUE THREAD

**Issue by rezende** [MindPointGroup/django-saml2-pro-auth#8]
from django docs,

https://docs.djangoproject.com/en/1.8/topics/auth/default/#django.contrib.auth.authenticate

def authenticate takes **credentials as argument

But in File "/django_saml2_pro_auth/views.py", line 42, in saml_login, it's being called by passing the request object
authenticate(request)

**Comment by defionscode** [comment]
This should happen when using django's default auth backend. In this case the default behavior is not being used since what is passed into authenticate() should be captured by https://github.com/MindPointGroup/django-saml2-pro-auth/blob/c06a316d18a08549e0f5af30e8456295efb08bd8/src/django_saml2_pro_auth/auth.py#L45

If you're trying to use this without expliciting setting it as an auth backend in your settings.py then you should see that error. Are you seeing the error even when specifying the auth backend? If so, would you mind sharing at least the relevant parts of your settings.py so I can try to replicate?

**Comment by rezende** [comment]
That might've been the issue. I will test it right now and will close this if it works.

Thanks a lot!

**Comment by rezende** [comment]
Didn't work, see comment above.

**Comment by defionscode** [comment]
ah! good catch, seems like the tests pass too. I have to fix an issue with coveralls which is what is causing it to appear as though the tests fail. I'll be able to get to this today. Thank you very much.

**Comment by defionscode** [comment]
closed by #10
